// File is autogenerated with `dub run spasm:bootstrap-webpack`
import {spasm as spa, decoders as decoder, encoders as encoder} from './spasm.js';

let spasm = spa;
const nodes = spasm.objects;

const addPtr = spasm.addObject;
export let jsExports = {
    env: {
        JSON_parse: (ctx) => {
            return addPtr(JSON.parse(nodes[ctx]));
        },
        StringToDouble: (len, off) => {
            const val = +decoder.string(len, off);
            return val;
        }
    }
}
